#ifndef __H3DViewerPluginsDialog__
#define __H3DViewerPluginsDialog__

/**
@file
Subclass of PluginsDialog, which is generated by wxFormBuilder.
*/

#include "H3DViewer.h"

/** Implementing PluginsDialog */
class H3DViewerPluginsDialog : public PluginsDialog
{
protected:
	// Handlers for PluginsDialog events.
	void OnInstalledPluginSelected( wxCommandEvent& event );
	void OnAddPluginButton( wxCommandEvent& event );
	void OnRemovePluginButton( wxCommandEvent& event );
	void OnDisablePluginCheckbox( wxCommandEvent& event );
	void OnURLEvent( wxTextUrlEvent& event );
public:
	/** Constructor */
	H3DViewerPluginsDialog( wxWindow* parent );

  bool addPlugin( const wxString &path, bool force_overwrite = false );
  bool removePlugin( const wxString &plugin_name );
};

#endif // __H3DViewerPluginsDialog__
