#ifndef __TreeViewerFieldValuesDialog__
#define __TreeViewerFieldValuesDialog__

#include <H3D/Node.h>

using namespace H3D;

/**
@file
Subclass of FieldValuesDialog, which is generated by wxFormBuilder.
*/

//#define DEFAULT_VALUES
#include "TreeViewer.h"

/** Implementing FieldValuesDialog */
class TreeViewerFieldValuesDialog : public FieldValuesDialog
{
public:
	/** Constructor */
	TreeViewerFieldValuesDialog( wxWindow* parent );

  void OnIdle( wxIdleEvent& event );
  virtual void OnCellEdit( wxGridEvent& event );

  void displayFieldsFromNode( Node * );
protected:
  
  TimeStamp last_fields_update;
#ifdef DEFAULT_VALUES
  AutoRef< Node > default_values_node;
#endif
  AutoRef< Node > displayed_node;

};

#endif // __TreeViewerFieldValuesDialog__
