#ifndef __TreeViewerFieldValuesDialog__
#define __TreeViewerFieldValuesDialog__

#include <H3D/Node.h>

using namespace H3D;

/**
@file
Subclass of FieldValuesDialog, which is generated by wxFormBuilder.
*/

#include "TreeViewer.h"

/** Implementing FieldValuesDialog */
class TreeViewerFieldValuesDialog : public FieldValuesDialog
{
public:
	/** Constructor */
	TreeViewerFieldValuesDialog( wxWindow* parent );

  void OnIdle( wxIdleEvent& event );
  virtual void OnCellEdit( wxGridEvent& event );

  void displayFieldsFromNode( Node * );
protected:
  Node *displayed_node;

};

#endif // __TreeViewerFieldValuesDialog__
