#ifndef __TreeViewerTreeViewDialog__
#define __TreeViewerTreeViewDialog__

#include <H3D/Node.h>
#include <map>
/**
@file
Subclass of TreeViewDialog, which is generated by wxFormBuilder.
*/

#include "TreeViewer.h"

/** Implementing TreeViewDialog */
class TreeViewerTreeViewDialog : public TreeViewDialog
{
public:
	/** Constructor */
	TreeViewerTreeViewDialog( wxWindow* parent );
  virtual void OnNodeSelected( wxTreeEvent& event );

  void showNodeAsTree( H3D::Node *n );
protected:
  void addSceneToTree( wxTreeItemId tree_id, H3D::Node *n );
  std::map< wxTreeItemIdValue, H3D::Node * > node_map;
};

#endif // __TreeViewerTreeViewDialog__
