#ifndef __TreeViewerTreeViewDialog__
#define __TreeViewerTreeViewDialog__

#include <H3D/Node.h>
#include <map>
#include <list>
/**
@file
Subclass of TreeViewDialog, which is generated by wxFormBuilder.
*/

#include "TreeViewer.h"

/** Implementing TreeViewDialog */
class TreeViewerTreeViewDialog : public TreeViewDialog
{
public:
	/** Constructor */
	TreeViewerTreeViewDialog( wxWindow* parent );
  virtual void OnNodeSelected( wxTreeEvent& event );

  void showEntireSceneAsTree( wxTreeItemId tree_id );
protected:
  void addNodeToTree( wxTreeItemId tree_id, H3D::Node *n, bool expand = true );
  void updateNodeTree( wxTreeItemId tree_id, std::list< H3D::Node *> );
  typedef  std::map< wxTreeItemIdValue, H3D::Node * > TreeIdMap;
  TreeIdMap node_map;
  wxTreeItemId bindable_tree_id;
};

#endif // __TreeViewerTreeViewDialog__
