#ifndef __TreeViewerMainFrame__
#define __TreeViewerMainFrame__

#include <H3D/Node.h>

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "TreeViewer.h"

/** Implementing MainFrame */
class TreeViewerMainFrame : public MainFrame
{
protected:
	// Handlers for MainFrame events.
	void OnIdle( wxIdleEvent& event );
	void OnOpenFile( wxCommandEvent& event );
	void OnClose( wxCommandEvent& event );
	void OnQuit( wxCommandEvent& event );
	
public:
	/** Constructor */
	TreeViewerMainFrame( wxWindow* parent );

};

#endif // __TreeViewerMainFrame__
