#ifndef __TreeViewerTreeViewDialog__
#define __TreeViewerTreeViewDialog__

#include <H3D/Node.h>
#include <map>
#include <list>
/**
@file
Subclass of TreeViewDialog, which is generated by wxFormBuilder.
*/

#include "TreeViewer.h"


using namespace H3D;
/** Implementing TreeViewDialog */
class TreeViewerTreeViewDialog : public TreeViewDialog
{
public:
	/** Constructor */
	TreeViewerTreeViewDialog( wxWindow* parent );
  virtual void OnNodeSelected( wxTreeEvent& event );
  virtual void OnCellEdit( wxGridEvent& event );
  void OnIdle( wxIdleEvent& event );

  void displayFieldsFromNode( Node * );
  void showEntireSceneAsTree( wxTreeItemId tree_id,
                              bool expand_new = true );

protected:
  // tree view members
  void addNodeToTree( wxTreeItemId tree_id, H3D::Node *n, bool expand = true );
  void updateNodeTree( wxTreeItemId tree_id, std::list< H3D::Node *>, bool expand_new = true );
  typedef  std::map< wxTreeItemIdValue, H3D::AutoRef< H3D::Node > > TreeIdMap;
  TreeIdMap node_map;
  wxTreeItemId bindable_tree_id;

  // field values members
  TimeStamp last_fields_update;
#ifdef DEFAULT_VALUES
  AutoRef< Node > default_values_node;
#endif
  AutoRef< Node > displayed_node;
};

#endif // __TreeViewerTreeViewDialog__
