/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /cvs/root/flex/flex/skel.c,v 1.2 2004/05/07 00:28:17 jkh Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5



/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <iostream>
using namespace std;
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};


/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer



static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>


/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 56
#define YY_END_OF_BUFFER 57
static yyconst short int yy_accept[297] =
    {   0,
        0,    0,   57,   55,   54,   54,   51,   55,   55,   51,
       53,   53,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   54,   51,    0,
        0,   52,   53,    0,   51,   53,   51,   51,   53,   53,
        0,    1,   51,   51,   51,   51,   51,   20,   51,   51,
       51,   51,   51,   51,   19,   51,   51,   51,   51,   53,
       53,   53,   51,   53,   51,    9,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   10,   51,   51,   51,   53,

       53,   53,   53,   51,   53,   53,   51,   51,   51,   51,
       51,    8,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   12,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,    2,   51,
       51,   51,   53,   53,   53,    0,   51,   51,   51,   53,
       53,   53,   51,   51,   51,    3,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   11,
       18,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   53,   51,   51,   51,   51,
        6,   51,    7,   21,   51,   51,   51,   51,   51,   28,

       51,   51,   31,   51,   51,   51,   36,   51,   51,   51,
       51,   51,   43,   51,   51,   46,   51,   51,   51,   51,
       51,   53,   53,   51,   51,   22,   51,   25,   26,   27,
       51,   51,   32,   33,   34,   35,    4,   37,   51,   40,
       41,   42,   51,   51,   47,   48,   49,   50,   51,   51,
       51,   51,   53,   53,   53,   51,   51,   51,   24,   51,
       30,   51,   39,   51,   45,   51,   51,   51,   51,    5,
       51,   51,   51,   51,   51,   51,   13,   51,   51,   51,
       51,   29,   51,   44,   51,   51,   14,   17,   23,   38,
       51,   16,   51,   51,   15,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    4,    4,    4,    1,    4,
        4,    4,    7,    2,    7,    8,    4,    9,   10,   11,
       12,   10,   10,   10,   10,   10,   10,    4,    4,    4,
        4,    4,    4,    4,   13,   14,   15,   16,   17,   18,
       19,    4,   20,    4,    4,   21,   22,   23,   24,   25,
        4,   26,   27,   28,   29,   30,    4,   31,    4,    4,
        1,   32,    1,    4,    4,    4,   33,   34,   35,   36,

       37,   38,   39,    4,   40,    4,    4,   41,   42,   43,
       44,   45,    4,   46,    4,   47,   48,    4,    4,   49,
       50,   51,    1,    4,    1,    4,    1,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,

        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4
    } ;

static yyconst int yy_meta[52] =
    {   0,
        1,    1,    2,    3,    1,    1,    3,    1,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    4,    4,    4,    4,    4,    4,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3
    } ;

static yyconst short int yy_base[301] =
    {   0,
        0,    0,  460,  560,   50,   52,    0,  427,    0,   54,
       90,   27,  430,  432,  438,  423,  434,   45,   51,  416,
      409,  410,  415,   49,  405,  388,  382,   75,    0,   55,
      426,    0,  138,  396,    0,   39,   54,    0,   55,    0,
        0,    0,  405,  408,   54,  404,  399,    0,  395,  137,
      391,  387,  381,  154,    0,  378,  389,   44,  358,  183,
       59,    0,  207,  244,  379,    0,  379,  385,  374,  376,
      386,  354,  353,  351,  353,   38,  349,  348,  344,  349,
      351,  366,   78,  358,  341,  340,  339,  341,   67,  337,
      336,  332,  338,  340,  358,    0,  327,  325,  327,  255,

      286,  317,   63,  353,  359,   74,  337,  333,  331,  336,
      326,    0,  307,  309,  300,  303,  313,  298,  308,  296,
      296,  299,  305,    0,  319,  314,  320,  292,  294,  285,
      288,  298,  283,  287,  274,  271,  274,  280,    0,  274,
      266,  264,    0,    0,   80,  404,    0,  441,   82,    0,
       83,   84,  288,  282,  286,    0,  280,  266,  262,  271,
      271,  264,  290,  264,  267,  259,  257,  105,  271,    0,
        0,  249,  242,  251,  251,  244,  270,  244,  247,  239,
      241,  107,  244,  252,  228,  489,    0,   89,   93,  257,
        0,  248,    0,    0,  226,  230,  223,  232,  257,    0,

      216,  218,    0,   90,   98,  242,    0,  206,  209,  201,
      202,  227,    0,  190,  193,    0,   99,  108,  194,   82,
      210,  500,  127,  210,  206,  205,  193,    0,    0,    0,
      189,  189,    0,    0,    0,    0,    0,  201,  189,    0,
        0,    0,  174,  174,    0,    0,    0,    0,  172,  170,
      163,  166,    0,  130,  140,  180,  183,  187,    0,  161,
        0,  185,    0,  159,    0,  151,  151,  155,  158,    0,
      170,  183,  153,  177,  144,  146,    0,  130,  125,  149,
      153,    0,  149,    0,  135,  109,    0,    0,    0,    0,
      111,    0,   81,   33,    0,  560,  547,  551,  555,   70

    } ;

static yyconst short int yy_def[301] =
    {   0,
      296,    1,  296,  296,  296,  296,  297,  298,  299,  297,
      296,   11,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  296,  297,  298,
      298,  299,  296,  298,   10,   11,   10,   10,   11,   11,
      300,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  298,
       11,   11,  297,  300,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  298,

      298,  298,  102,   63,   64,  105,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  102,  102,  102,  298,   10,   63,  148,  105,
      105,  105,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  146,  148,  148,  148,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,

      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  146,  222,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  222,  222,  222,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,    0,  296,  296,  296,  296

    } ;

static yyconst short int yy_nxt[612] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,    4,   11,   12,
       12,   12,   13,    7,   14,   15,   16,   17,    7,   18,
        7,   19,   20,    7,   21,   22,   23,   24,   25,    7,
        7,    4,    7,    7,    7,    7,    7,    7,    7,   26,
        7,    7,    7,   27,    7,    7,    7,    7,    7,    7,
        7,   28,   28,   28,   28,   33,   33,  296,   34,   60,
       35,   36,   37,   35,   35,   35,   47,   49,   50,  296,
       38,   48,   55,   64,   56,  296,   28,   28,   67,  117,
      118,   68,  295,   97,   63,  296,   31,  296,   98,  296,
       38,   33,   33,  146,   34,  125,   39,   36,   40,   39,

       39,   39,   63,  296,  296,  126,   36,  296,  132,  133,
      146,  146,   29,  296,  296,  204,  205,  217,  218,   29,
       41,  294,  296,   29,  250,  233,   36,  234,  146,  251,
       29,  296,  296,  235,  245,  236,  246,   29,   41,   33,
       33,   29,   34,  247,   61,  248,   62,   61,   61,   61,
       72,   73,   74,  293,   75,  292,   76,   30,  291,   77,
       30,  290,   78,   79,   80,  289,   81,   85,   86,   87,
       30,   88,  288,   89,  287,   30,   90,  286,   30,   91,
       92,   93,  285,   94,  100,  100,  284,  101,   30,  102,
      283,  103,  102,  102,  102,  282,  281,  280,  279,  278,

      277,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  264,   31,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  263,  262,  261,  260,  259,
      258,  257,  256,  252,  249,  244,  243,  242,  241,  104,
      104,  104,  104,  104,  104,   33,   33,  240,   34,  239,
       61,  238,  105,  106,  106,  106,  100,  100,  237,  101,
      232,  102,  231,  103,  102,  102,  102,  230,  229,  228,
      227,  226,  225,  224,  221,  220,  219,  216,  215,  214,
      213,  212,  211,  210,  209,  208,   31,  100,  100,  207,
      101,  206,  102,  203,  103,  102,  102,  102,  202,  201,

      200,  199,  198,  197,  196,  195,  194,  193,  192,  191,
      190,  185,  184,  183,  182,  181,  180,   31,  100,  100,
      179,  101,  178,  143,  144,  145,  143,  143,  143,  177,
      176,  175,  174,  144,  173,  172,  171,  170,  169,  168,
      167,  166,  165,  164,  163,  162,  161,  160,   31,  159,
      158,  157,  156,  144,   33,   33,  155,   34,  154,  147,
      153,  148,  149,  149,  149,   39,   36,  150,  151,  151,
      151,  142,  141,  140,  139,  152,  138,  137,  136,  135,
      134,  131,  130,  129,  128,  127,  124,  123,  122,   41,
      121,  120,  119,  116,  115,  152,  114,  113,  112,  111,

      110,  109,  108,  107,   99,   96,   95,   41,   60,   84,
       83,   82,  186,  186,  186,  186,  186,  186,  186,  186,
      186,  186,   71,   70,   69,   66,   65,   31,  296,   59,
       58,   57,   54,   53,   52,   31,  186,  186,  186,  186,
      186,  186,   33,   33,   51,   34,   46,   35,   36,  187,
      188,  188,  188,   45,   44,   43,   42,  189,   31,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,   63,  296,  296,  296,  296,  296,  189,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,   63,
      100,  100,  296,  101,  296,  102,  296,  222,  223,  223,

      223,  100,  100,  296,  101,  296,  143,  144,  253,  254,
      254,  254,  296,  296,  296,  296,  255,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      146,  296,  296,  296,  296,  296,  255,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  146,   29,
       29,   30,   30,   30,   30,   32,  296,   32,   32,    3,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,

      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296
    } ;

static yyconst short int yy_chk[612] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    5,    6,    6,   10,   10,   12,   10,   30,
       10,   10,   10,   10,   10,   10,   18,   19,   19,   36,
       10,   18,   24,  300,   24,   12,   28,   28,   45,   76,
       76,   45,  294,   58,   37,   39,   30,   36,   58,   61,
       10,   11,   11,  103,   11,   83,   11,   11,   11,   11,

       11,   11,   37,   39,  106,   83,   11,   61,   89,   89,
      145,  103,  149,  151,  152,  168,  168,  182,  182,  188,
       11,  293,  106,  189,  220,  204,   11,  204,  145,  220,
      149,  151,  152,  205,  217,  205,  217,  188,   11,   33,
       33,  189,   33,  218,   33,  218,   33,   33,   33,   33,
       50,   50,   50,  291,   50,  286,   50,  223,  285,   50,
      254,  283,   50,   50,   50,  281,   50,   54,   54,   54,
      255,   54,  280,   54,  279,  223,   54,  278,  254,   54,
       54,   54,  276,   54,   60,   60,  275,   60,  255,   60,
      274,   60,   60,   60,   60,  273,  272,  271,  269,  268,

      267,  266,  264,  262,  260,  258,  257,  256,  252,  251,
      250,  249,  244,  243,   60,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,  239,  238,  232,  231,  227,
      226,  225,  224,  221,  219,  215,  214,  212,  211,   63,
       63,   63,   63,   63,   63,   64,   64,  210,   64,  209,
       64,  208,   64,   64,   64,   64,  100,  100,  206,  100,
      202,  100,  201,  100,  100,  100,  100,  199,  198,  197,
      196,  195,  192,  190,  185,  184,  183,  181,  180,  179,
      178,  177,  176,  175,  174,  173,  100,  101,  101,  172,
      101,  169,  101,  167,  101,  101,  101,  101,  166,  165,

      164,  163,  162,  161,  160,  159,  158,  157,  155,  154,
      153,  142,  141,  140,  138,  137,  136,  101,  102,  102,
      135,  102,  134,  102,  102,  102,  102,  102,  102,  133,
      132,  131,  130,  102,  129,  128,  127,  126,  125,  123,
      122,  121,  120,  119,  118,  117,  116,  115,  102,  114,
      113,  111,  110,  102,  104,  104,  109,  104,  108,  104,
      107,  104,  104,  104,  104,  105,  105,  105,  105,  105,
      105,   99,   98,   97,   95,  105,   94,   93,   92,   91,
       90,   88,   87,   86,   85,   84,   82,   81,   80,  105,
       79,   78,   77,   75,   74,  105,   73,   72,   71,   70,

       69,   68,   67,   65,   59,   57,   56,  105,  146,   53,
       52,   51,  146,  146,  146,  146,  146,  146,  146,  146,
      146,  146,   49,   47,   46,   44,   43,   34,   31,   27,
       26,   25,   23,   22,   21,  146,  146,  146,  146,  146,
      146,  146,  148,  148,   20,  148,   17,  148,  148,  148,
      148,  148,  148,   16,   15,   14,   13,  148,    8,    3,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  148,    0,    0,    0,    0,    0,  148,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  148,
      186,  186,    0,  186,    0,  186,    0,  186,  186,  186,

      186,  222,  222,    0,  222,    0,  222,  222,  222,  222,
      222,  222,    0,    0,    0,    0,  222,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      222,    0,    0,    0,    0,    0,  222,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  222,  297,
      297,  298,  298,  298,  298,  299,    0,  299,  299,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,

      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "vrml.l"
#define INITIAL 0
#line 561 "lex.yy.cc"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif


#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yyFlexLexer::yylex()
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 14 "vrml.l"



#include "vrml.hpp"
void setyylval(char *);


#line 696 "lex.yy.cc"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = &cin;

		if ( ! yyout )
			yyout = &cout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 297 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 560 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 21 "vrml.l"
return AS;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 22 "vrml.l"
return TRUE;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 23 "vrml.l"
return FALSE;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 24 "vrml.l"
return PROFILE;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 25 "vrml.l"
return COMPONENT;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 26 "vrml.l"
return EXPORT;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 27 "vrml.l"
return IMPORT;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 28 "vrml.l"
return META;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 29 "vrml.l"
return DEF;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 30 "vrml.l"
return USE;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 31 "vrml.l"
return PROTO;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 32 "vrml.l"
return VRMLNULL;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 33 "vrml.l"
return inputOnly;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 34 "vrml.l"
return outputOnly;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 35 "vrml.l"
return initializeOnly;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 36 "vrml.l"
return inputOutput;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 37 "vrml.l"
return EXTERNPROTO;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 38 "vrml.l"
return ROUTE;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 39 "vrml.l"
return TO;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 40 "vrml.l"
return IS;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 41 "vrml.l"
return TMFBool;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 42 "vrml.l"
return TMFColor;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 43 "vrml.l"
return TMFColorRGBA;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 44 "vrml.l"
return TMFDouble;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 45 "vrml.l"
return TMFFloat;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 46 "vrml.l"
return TMFImage;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 47 "vrml.l"
return TMFInt32;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 48 "vrml.l"
return TMFNode;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 49 "vrml.l"
return TMFRotation;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 50 "vrml.l"
return TMFString;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 51 "vrml.l"
return TMFTime;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 52 "vrml.l"
return TMFVec2d;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 53 "vrml.l"
return TMFVec2f;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 54 "vrml.l"
return TMFVec3d;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 55 "vrml.l"
return TMFVec3f;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 56 "vrml.l"
return TSFBool;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 57 "vrml.l"
return TSFColor;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 58 "vrml.l"
return TSFColorRGBA;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 59 "vrml.l"
return TSFDouble;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 60 "vrml.l"
return TSFFloat;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 61 "vrml.l"
return TSFImage;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 62 "vrml.l"
return TSFInt32;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 63 "vrml.l"
return TSFNode;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 64 "vrml.l"
return TSFRotation;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 65 "vrml.l"
return TSFString;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 66 "vrml.l"
return TSFTime;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 67 "vrml.l"
return TSFVec2d;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 68 "vrml.l"
return TSFVec2f;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 69 "vrml.l"
return TSFVec2d;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 70 "vrml.l"
return TSFVec3f;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 73 "vrml.l"
/*printf("ID=%s\n",yytext);*/ setyylval(yytext); return ID;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 75 "vrml.l"
/* eat up comments */
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 78 "vrml.l"
/*printf("VAL=%s\n",yytext);*/ setyylval(yytext); return STRING;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 80 "vrml.l"
/* eat up whitespace */
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 82 "vrml.l"
return yytext[0];
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 86 "vrml.l"
ECHO;
	YY_BREAK
#line 1059 "lex.yy.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */

yyFlexLexer::yyFlexLexer( istream* arg_yyin, ostream* arg_yyout )
	{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 1;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = 0;

	yy_current_buffer = 0;

#ifdef YY_USES_REJECT
	yy_state_buf = new yy_state_type[YY_BUF_SIZE + 2];
#else
	yy_state_buf = 0;
#endif
	}

yyFlexLexer::~yyFlexLexer()
	{
	delete yy_state_buf;
	yy_delete_buffer( yy_current_buffer );
	}

void yyFlexLexer::switch_streams( istream* new_in, ostream* new_out )
	{
	if ( new_in )
		{
		yy_delete_buffer( yy_current_buffer );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE ) );
		}

	if ( new_out )
		yyout = new_out;
	}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
	{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
	}

void yyFlexLexer::LexerOutput( const char* buf, int size )
	{
	(void) yyout->write( buf, size );
	}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

int yyFlexLexer::yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

yy_state_type yyFlexLexer::yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 297 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 297 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 296);

	return yy_is_jam ? 0 : yy_current_state;
	}


void yyFlexLexer::yyunput( int c, register char* yy_bp )
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}


int yyFlexLexer::yyinput()
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


void yyFlexLexer::yyrestart( istream* input_file )
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


void yyFlexLexer::yy_load_buffer_state()
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( istream* file, int size )
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


extern "C" int isatty YY_PROTO(( int ));
void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, istream* file )

	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

	b->yy_is_interactive = 0;
	}


void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#endif


#ifndef YY_NO_SCAN_STRING
#endif


#ifndef YY_NO_SCAN_BYTES
#endif


#ifndef YY_NO_PUSH_STATE
void yyFlexLexer::yy_push_state( int new_state )
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
void yyFlexLexer::yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
int yyFlexLexer::yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif


void yyFlexLexer::LexerError( yyconst char msg[] )
	{
	cerr << msg << '\n';
	exit( YY_EXIT_FAILURE );
	}


/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 86 "vrml.l"



